### ISSUE TITLE
Close button shown incorrectly

### ISSUE THREAD

**Issue by huoyaoyuan** [4ux-nbIx/AvalonDock.Themes.VS2013#4]
When I use a LayoutDocument with CanClose=False, the close button has still been shown, but unable to click.
@tgjones could you fix it in your fork?

**Comment by EchterAgo** [comment]
@huoyaoyuan can you confirm the issue is fixed by #8 ?

**Comment by huoyaoyuan** [comment]
@EchterAgo Yes, this issue is now fixed.
