### ISSUE TITLE
Update Extended.Wpf.Toolkit

### ISSUE THREAD

**Issue by wojtpl2** [4ux-nbIx/AvalonDock.Themes.VS2013#9]
Current you use version:
`<package id="Extended.Wpf.Toolkit" version="2.6" targetFramework="net40-Client" />`

There is new version 2.9.0 - https://www.nuget.org/packages/Extended.Wpf.Toolkit/
`<package id="Extended.Wpf.Toolkit" version="2.9" targetFramework="net461" />`

New version has new feathures, for example you can set ShowHeader on LayoutDocumentPane.
Are you planning to update Extended.Wpf.Toolkit?

**Comment by 4ux-nbIx** [comment]
Hi,
Unfortunately I've got lot's of other stuff to do right now, but you can always submit a pull request!.. ;)

**Comment by wojtpl2** [comment]
Ok. I'll try.

**Comment by 4ux-nbIx** [comment]
Thanks for the pull request! I've just noticed that Xceed had unlisted their free WPF Toolkit package and only commercial Toolkit Plus packages are available now. Did they deprecate the free version of Avalon Dock and stuff? Do you know anything about it?

**Comment by wojtpl2** [comment]
New version was released at June 14, 2016. There is changes list: http://wpftoolkit.codeplex.com/wikipage?title=Improvements290

On the page http://wpftoolkit.codeplex.com/ is information "The free, open source Community Edition is provided under the Microsoft Public License". There is also information about nuget package. 

I don't have any other information.

**Comment by 4ux-nbIx** [comment]
Good, looks like the Community Edition is still available, but unlisting it from NuGet looks suspicious...

**Comment by wojtpl2** [comment]
When you publish a new package on nuget?

**Comment by 4ux-nbIx** [comment]
Good question! I think should do it soon, because it seems like people started using it. I'll try to publish it this week...

**Comment by wojtpl2** [comment]
Free Extended WPF Toolkit 2.9.0 is available now. https://www.nuget.org/packages/Extended.Wpf.Toolkit/

**Comment by Kibnet** [comment]
I think the task can be closed.
